[package]
name = "main"
version = "0.0.1"

[dependencies]
libc = "0.2.51"
rand = "0.6"
statistical = "1.0.0"
time = "0.1"
quickersort = "3.0"
is_sorted = "0.1.1"
num = "0.2.0"
polynomial = "0.1.0"

#[dev-dependencies]
#criterion = "0.2"